### ISSUE TITLE
1.16.2 & 1.16.3

### ISSUE THREAD

**Issue by RDIL** [RDIL/Cherry#25]
We need to support 1.16.2 and 1.16.3.

It will require a lot of changes related to the GUIs, they seem to have changed a ton.

**Comment by ocelik94** [comment]
Hi,
I should be aiming to upgrade the version "20w14infinite" to 1.16.2/1.16.3 right? I guess I will have to update "Maple".

Looks like a funny first issue for me <3

**Comment by RDIL** [comment]
Hey @Andrioshe,
You would create a copy of maple, name it after a different tree, and do it there.

**Comment by ocelik94** [comment]
I am actually fighting with the following line because "Style" has private access and I don't know how get around this the best way.

```
    public static LiteralText getTitleTextComponent() {
        Style titleStyle = new Style()
                .setBold(true)
                .setUnderline(true)
                .setColor(Formatting.RED);
        return (LiteralText) new LiteralText("General Settings").setStyle(titleStyle);
    }
```

I tried to rewrite the function but it doesn't seem to work at all

```
    public static LiteralText getTitleTextComponent() {
        return (LiteralText) new LiteralText("FPS Widget").styled(
                style -> style.withBold(true)
                        .withUnderline(true)
                        .withColor(Formatting.RED));
    }
```

**Comment by RDIL** [comment]
Hey @Andrioshe,
I'll try to make an accessor mixin to fix it.  

Can you push your changes to a fork so I can work on it as well?  

Thanks again :D

**Comment by ocelik94** [comment]
https://github.com/Andrioshe/Cherry

I am working on a fork on my side. I have create a PR when I am finished, right?

**Comment by RDIL** [comment]
Yup.  I'll try to fix this in the meantime.

**Comment by RDIL** [comment]
@Andrioshe I fixed it but can't edit your fork.  Can you open a pull request?

**Comment by Andrioshe** [comment]
#26
